### ISSUE TITLE
Please update logs so they contain a timestamp

### ISSUE THREAD

**Issue by RickJWagner** [redhat-developer/codeready-workspaces-theia#6]
Logs for theia do not contain a timestamp, which precludes them from being of much use in diagnosing performance issues.  (See example below.)

Please add a timestamp.

// We have no idea how long this stuff takes.

[rick@unknown48A472AC8CFD 02554238]$ oc logs workspacekjck253dtgnb8hxi.php-8ccfcb798-m8j8m -c theia-ide806
root INFO Theia app listening on http://0.0.0.0:3100.
root INFO unzipping the plug-in 'eclipse_che_ports_plugin.theia' to directory: /tmp/theia-unpacked/eclipse_che_ports_plugin.theia
root INFO unzipping the plug-in 'eclipse_che_theia_containers_plugin.theia' to directory: /tmp/theia-unpacked/eclipse_che_theia_containers_plugin.theia
root INFO unzipping the plug-in 'eclipse_che_theia_factory_plugin.theia' to directory: /tmp/theia-unpacked/eclipse_che_theia_factory_plugin.theia
root INFO unzipping the plug-in 'eclipse_che_theia_ssh_plugin.theia' to directory: /tmp/theia-unpacked/eclipse_che_theia_ssh_plugin.theia
root INFO unzipping the plug-in 'eclipse_che_welcome_plugin.theia' to directory: /tmp/theia-unpacked/eclipse_che_welcome_plugin.theia
root INFO unzipping the plug-in 'task_plugin.theia' to directory: /tmp/theia-unpacked/task_plugin.theia
root INFO unzipping the plug-in 'theia_yeoman_plugin.theia' to directory: /tmp/theia-unpacked/theia_yeoman_plugin.theia
root INFO unzipping the VS Code extension 'vscode-git-1.3.0.1.vsix' to directory: /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/theia-unpacked/eclipse_che_ports_plugin.theia
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/theia-unpacked/eclipse_che_theia_containers_plugin.theia
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/theia-unpacked/eclipse_che_theia_factory_plugin.theia

**Comment by RickJWagner** [comment]
Related product tracker: 
https://issues.redhat.com/browse/CRW-614

**Comment by nickboldt** [comment]
Fixed in master https://github.com/eclipse/che-theia/commit/6d136b2c9b7f2e60b3f506537a2c5e57a6806a29

Cherrypicked to 7.9.x:

https://github.com/eclipse/che-theia/commit/22b62ea954d539133f21dfe69148203dbf69c006
